if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"female","path":"/etc/segmentation/contexthub/female"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("equal.string",ContextHub.SegmentEngine.Property("profile\/gender"),"female"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"female-over-30","path":"/etc/segmentation/contexthub/female-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"female-under-30","path":"/etc/segmentation/contexthub/female-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"male","path":"/etc/segmentation/contexthub/male"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("equal.string",ContextHub.SegmentEngine.Property("profile\/gender"),"male"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"male-over-30","path":"/etc/segmentation/contexthub/male-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"male-under-30","path":"/etc/segmentation/contexthub/male-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"order-value-75-to-100","path":"/etc/segmentation/contexthub/order-value-75-to-100"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("cart\/totalPriceFloat"),"75"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("cart\/totalPriceFloat"),"100"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"order-value-over-100","path":"/etc/segmentation/contexthub/order-value-over-100"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than.number",ContextHub.SegmentEngine.Property("cart\/totalPriceFloat"),"100"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"over-30","path":"/etc/segmentation/contexthub/over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("profile\/age"),"30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer","path":"/etc/segmentation/contexthub/summer"}, ContextHub.SegmentEngine.Operator("or",ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"40"),ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"4"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"9")),ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"\-38"),ContextHub.SegmentEngine.Operator("or",ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"4"),ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"9"))),ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"\-38"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"40")))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-female","path":"/etc/segmentation/contexthub/summer-female"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-female-over-30","path":"/etc/segmentation/contexthub/summer-female-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-female-under-30","path":"/etc/segmentation/contexthub/summer-female-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-male","path":"/etc/segmentation/contexthub/summer-male"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-male-over-30","path":"/etc/segmentation/contexthub/summer-male-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"summer-male-under-30","path":"/etc/segmentation/contexthub/summer-male-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/summer"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"under-30","path":"/etc/segmentation/contexthub/under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("profile\/age"),"30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter","path":"/etc/segmentation/contexthub/winter"}, ContextHub.SegmentEngine.Operator("or",ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("greater\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"40"),ContextHub.SegmentEngine.Operator("or",ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"9"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"4"))),ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"\-38"),ContextHub.SegmentEngine.Operator("greater\-than\-or\-equal.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"4"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("surferinfo\/month"),"9")),ContextHub.SegmentEngine.Operator("greater\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"70"),ContextHub.SegmentEngine.Operator("less\-than.number",ContextHub.SegmentEngine.Property("geolocation\/latitude"),"\-50"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-female","path":"/etc/segmentation/contexthub/winter-female"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-female-over-30","path":"/etc/segmentation/contexthub/winter-female-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-female-under-30","path":"/etc/segmentation/contexthub/winter-female-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/female"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-male","path":"/etc/segmentation/contexthub/winter-male"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-male-over-30","path":"/etc/segmentation/contexthub/winter-male-over-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/over\-30"))); };
if (window.ContextHub && ContextHub.SegmentEngine) { ContextHub.SegmentEngine.Segment({"name":"winter-male-under-30","path":"/etc/segmentation/contexthub/winter-male-under-30"}, ContextHub.SegmentEngine.Operator("and",ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/winter"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/male"),ContextHub.SegmentEngine.SegmentReference("\/etc\/segmentation\/contexthub\/under\-30"))); };
CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment16","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment1","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment2","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment3","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment4","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment5","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment6","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment7","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment8","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment9","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment10","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment11","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment12","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment13","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment14","( true )",0);

CQ_Analytics.SegmentMgr.register("/etc/segmentation/samsung/audiencesegment15","( true )",0);

